# Generated by Django 5.2.5 on 2025-08-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vedynamicform',
            table='ve_dynamic_form',
        ),
        migrations.AlterModelTable(
            name='vedynamicformfield',
            table='ve_dynamic_form_field',
        ),
        migrations.AlterModelTable(
            name='veemployee',
            table='ve_employee',
        ),
        migrations.AlterModelTable(
            name='veemployeefieldvalue',
            table='ve_employee_field_value',
        ),
        migrations.AlterModelTable(
            name='vefieldtype',
            table='ve_field_type',
        ),
    ]
