# Generated by Django 5.2.5 on 2025-08-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_vedynamicform_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vedynamicformfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
