# Generated by Django 5.2.5 on 2025-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_vedynamicformfield_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veemployeefieldvalue',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
